version: '2'
services:

    # Application container
    php:
        build: .
        restart: unless-stopped
        image: lalamove_test
        volumes:
            - ./:/server/http
        ports:
            - "80:80"
            - "443:443"
        links:
            - mongodb
        environment:
            DEBUG: 'false'
         
    
    mongodb:
        image: mvertes/alpine-mongo:3.2.3
        restart: unless-stopped
        ports:
            - "27017:27017"
    
